### ISSUE TITLE
how can I contact you?

### ISSUE THREAD

**Issue by saifshabsug** [Egor-Skriptunoff/LGS_extension#4]
please how can I contact you for some help its urgent, big thanks

**Comment by Egor-Skriptunoff** [comment]
If you have a question about `LGS_extension` project, just create an issue and ask here.  
If you have a general question about programming in LGS/GHUB you should ask a question on StackOverflow and mark it with [`logitech-gaming-software` tag](https://stackoverflow.com/questions/tagged/logitech-gaming-software), I will see your question there.  
You can send a private message to me via email: `egor.skriptunoff` at `gmail.com`.
