### ISSUE TITLE
beep function

### ISSUE THREAD

**Issue by ropucyka** [Egor-Skriptunoff/LGS_extension#5]
Егор, ни в LGS ни GHUB нет поддержки такой функции, ты помогаешь людям с этим софтом, например FastSleep.
Так есть ли возможность сделать функцию beep (сигнал через динамики), ты можешь такое создать для LGS?

**Comment by Egor-Skriptunoff** [comment]
В LGS и GHUB можно сделать макро, запускающий произвольный внешний exe-файл с параметрами.  
Создай .wav-файл с нужным звуком и запусти его через какой-нибудь медиа-плеер или vlc.exe или что-нибудь ещё.  
Из Lua-кода такой макро можно вызвать через `PlayMacro`
